// Class automatically generated by Dev-C++ New Class wizard

#ifndef ARRAYLIST_H
#define ARRAYLIST_H

#include "canguro.h"
/*
 * No description
 */
namespace KangaParty
{
class ArrayList
{
    private:  
      Canguro **canguroList;
      int _length; //cantidad de CANGUROS
      int arrayLength;
      
	public:
           
           
		ArrayList(int length);
		~ArrayList();
		
		//===De Interfaz===
		int size();
		void add(int index, Canguro * nuevoCang);
		Canguro get(int index);
		bool isEmpty();
		void remove(int position);
		//=================
		
		void print();
		void print(int index);
};
}
#endif // ARRAYLIST_H
