// Class automatically generated by Dev-C++ New Class wizard

#ifndef CANGURO_H
#define CANGURO_H

#include <string> 

using namespace std;

/*
 * No description
 */

namespace KangaParty
{
class Canguro
	{
          int _id;
          int jumpHeight;
          string nombre;
       
		public:
			
			Canguro(int id);
			Canguro(const Canguro& source); //contructor copia
			Canguro& operator= (const Canguro &source); //asignación		
			~Canguro(); //destructor
			string show(string atributo);
		
	};
}

#endif // CANGURO_H
