// Class automatically generated by Dev-C++ New Class wizard

#ifndef ARRAYLIST_H
#define ARRAYLIST_H

#include "canguro.h"
#include "IListable.h"
/*
 * No description
 */
namespace KangaParty
{
class ArrayList: public IListable
{
    private:  
      Canguro **canguroList; 
      int _length; //cantidad de CANGUROS
      int arrayLength;
      
	public:
           
           
		ArrayList(int length);
		~ArrayList();
		ArrayList& operator= (const ArrayList& source);
		
		//===De Interfaz===
		virtual int size();
		virtual void add(int index, Canguro * nuevoCang);
		virtual Canguro get(int index);
		virtual bool isEmpty();
		virtual void remove(int position);
		virtual void printList();
		virtual void consulta();
		virtual Canguro* getPointer(int index);
		//=================
		
		void print();
		void print(int index);
		
};
}
#endif // ARRAYLIST_H
