// Class automatically generated by Dev-C++ New Class wizard

#ifndef LINKEDNODE_H
#define LINKEDNODE_H

#include "canguro.h"

namespace KangaParty
{
class LinkedNode
{
        
public:
       LinkedNode* _next;
        Canguro* _content;
        LinkedNode(Canguro * content, LinkedNode * next);
        //Constructor con puntero a "null"
        LinkedNode(Canguro * content);
		~LinkedNode();
		//Copia
		LinkedNode(const LinkedNode& source);
		//Sobrecarga operador =
		LinkedNode& operator= (const LinkedNode &source);
		LinkedNode* getNext();
		void setNext(LinkedNode * next);
		Canguro* getContent();
		//void setContent(Canguro * content,bool destroy);
		void mostrarTodo();
		void preDestroy();
		
};
}
#endif // LINKEDNODE_H
