// Class automatically generated by Dev-C++ New Class wizard

#ifndef HEAPSORT1_H
#define HEAPSORT1_H

#include "iordenable.h"


class HeapSort1 : public IOrdenable
{
	public:
		HeapSort1();
		~HeapSort1();
		virtual void sort(int* data, int length);
		void InvertedHeap(int* data, int length);
		void removeMax(int* data, int length, int HeapLength);
		void Hundir(int* data, int At, int HeapLength);
		void Flotar(int* data, int At);
		
};

#endif // HEAPSORT1_H
