// Class automatically generated by Dev-C++ New Class wizard

#ifndef RBT_H
#define RBT_H

/*
 * No description
 */
class RBT
{
	public:
		// class constructor
		RBT();
		// class destructor
		~RBT();
};

#endif // RBT_H
