// Class automatically generated by Dev-C++ New Class wizard

#include "rbt.h" // class's header file

// class constructor
// RBT: Red-Black three
RBT::RBT()
{
	// insert your code here
}

// class destructor
RBT::~RBT()
{
	// insert your code here
}
