// Class automatically generated by Dev-C++ New Class wizard

#include "treap.h" // class's header file

// class constructor
Treap::Treap()
{
	// insert your code here
}

// class destructor
Treap::~Treap()
{
	// insert your code here
}
