// Class automatically generated by Dev-C++ New Class wizard

#ifndef TREAP_H
#define TREAP_H

/*
 * No description
 */
class Treap
{
	public:
		// class constructor
		Treap();
		// class destructor
		~Treap();
};

#endif // TREAP_H
